Initial commit

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,41 +1,38 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-apt-get update
-apt-get install -y tree
+# fail fast
+set -e
 
-tree / > /tmp/before.csv
+# debug
+# set -x
 
-## fail fast
-#set -e
-#
-## debug
-## set -x
-#
-## parse and derive params
-#BUILD_DIR=$1
-#CACHE_DIR=$2
-#ENV_DIR=$3
-#
-#LP_DIR=`cd $(dirname $0); cd ..; pwd`
-#
-#function error() {
-#  echo " !     $*" >&2
-#  exit 1
-#}
-#
-#function topic() {
-#  echo "-----> $*"
-#}
-#
-#function indent() {
-#  c='s/^/       /'
-#  case $(uname) in
-#    Darwin) sed -l "$c";;
-#    *)      sed -u "$c";;
-#  esac
-#}
-#
+# parse and derive params
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
+
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
+
+function topic() {
+  echo "-----> $*"
+}
+
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+echo "$BUILD_DIR" > /tmp/del.txt
+
 #PACKAGES="gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libcairo-gobject2 libxinerama1 libgtk2.0-0 libpangoft2-1.0-0 libthai0 libpixman-1-0 libxcb-render0 libharfbuzz0b libdatrie1 libgraphite2-3 libgbm1"
 #
 #APT_CACHE_DIR="$CACHE_DIR/apt/cache"
